# Generated by Django 4.2 on 2023-08-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demande',
        ),
        migrations.DeleteModel(
            name='produit',
        ),
    ]
