# Generated by Django 4.2 on 2023-08-09 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0004_delete_demande_delete_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('desc', models.TextField()),
                ('prix', models.IntegerField()),
                ('a_prix', models.IntegerField()),
                ('promo', models.BooleanField(default=False)),
                ('pack', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='photos')),
            ],
            options={
                'verbose_name': 'produits',
            },
        ),
        migrations.CreateModel(
            name='demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomprenom', models.CharField(max_length=500)),
                ('num', models.IntegerField()),
                ('adress', models.TextField()),
                ('pro', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='backend.produit')),
            ],
            options={
                'verbose_name': 'demandes',
            },
        ),
    ]
