# Generated by Django 4.2 on 2023-08-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_demande_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='adress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='nomprenom',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='pro',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
