# Generated by Django 4.2 on 2023-08-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_demande_adress_alter_demande_nomprenom_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demande',
            options={'verbose_name': 'demande'},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'verbose_name': 'produit'},
        ),
    ]
