# Generated by Django 4.2 on 2023-08-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_demande_options_alter_produit_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demande',
        ),
        migrations.DeleteModel(
            name='produit',
        ),
    ]
