# Generated by Django 4.2 on 2023-08-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='a_prix',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
