# Generated by Django 4.2 on 2023-08-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_produit_a_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='adress',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='demande',
            name='nomprenom',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='demande',
            name='num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='demande',
            name='pro',
            field=models.CharField(max_length=500),
        ),
    ]
