# Generated by Django 4.2 on 2023-08-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_produit_a_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='a_prix',
            field=models.IntegerField(),
        ),
    ]
