# Generated by Django 4.2 on 2023-08-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_produit_a_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='pro',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
